version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - timely_class_network

  # pgAdmin 4
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: itzmesojib@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Sojib@123
    ports:
      - "5050:80"
      - "5051:443"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - timely_class_network

  # Redis Cache
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "900", "1"]
    networks:
      - timely_class_network

  # Users Microservice
  users-service:
    build:
      context: ./services/User
      dockerfile: Dockerfile
    container_name: users_service
    restart: on-failure
    env_file:
      - ./services/User/.env
    ports:
      - "5001:5001"
    volumes:
      - ./services/User:/app
      - /app/node_modules
    command: yarn dev
    depends_on:
      - postgres
      - redis
    networks:
      - timely_class_network

  # Schedule Microservice
  schedule-service:
    build:
      context: ./services/Schedule
      dockerfile: Dockerfile
    container_name: schedule_service
    restart: on-failure
    env_file:
      - ./services/Schedule/.env
    ports:
      - "5002:5002"
    volumes:
      - ./services/Schedule:/app
      - /app/node_modules
    command: yarn dev
    depends_on:
      - postgres
      - redis
      - users-service
    networks:
      - timely_class_network

  # Kong Database (for Kong Gateway)
  kong-database:
    image: postgres:14
    container_name: kong_db
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5433:5432"
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - timely_class_network

  # Kong Migrations
  kong-migrations:
    image: kong:3.3
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database
    networks:
      - timely_class_network

  # Kong Gateway
  kong:
    image: kong:3.3
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - kong-migrations
    networks:
      - timely_class_network

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  kong_data:

networks:
  timely_class_network:
    driver: bridge
